import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Mail, Phone, Sparkles } from "lucide-react";
import Navbar from "@/components/Navbar"; import Footer from "@/components/Footer";

const experiences = [
  ["Winery Experiences", "Unhurried tastings, long lunches, and a view worth staying for.", "/images/hill-country-vineyard.png"],
  ["Brewery & Distillery Tours", "Follow a curious palate through the Hill Country’s most memorable pours.", "/images/hill-country-evening.png"],
  ["Weddings", "A beautiful beginning, made easy from the first arrival to the last goodbye.", "/images/hill-country-evening.png"],
  ["Concerts", "Make the evening last a little longer—with no rush home.", "/images/hill-country-evening.png"],
  ["Airport Transportation", "A calm welcome to the place you came to escape to.", "/images/hill-country-weekend-hero.png"],
  ["Custom Itineraries", "The best kind of plan leaves room for a beautiful surprise.", "/images/hill-country-vineyard.png"],
];
const destinations = [["Wimberley", "Creekside mornings, artful shops, and limestone paths made for wandering."], ["Driftwood", "Vineyard tables, live oaks, and the easy rhythm of a long Hill Country lunch."], ["Dripping Springs", "Distilleries, breweries, and the kind of open sky that resets everything."], ["Fredericksburg", "A classic weekend of tastings, Main Street charm, and vineyard horizons."]];
const reasons = [["01", "Local Knowledge", "The back roads, favorite views, and hidden corners that make a day feel personal."], ["02", "Private Experience", "Your people, your pace, and a day that belongs entirely to you."], ["03", "Flexible Schedule", "Stay for one more song, one more pour, one more perfect sunset."], ["04", "Comfortable Transportation", "The quiet ease of knowing every beautiful mile is already taken care of."]];

export default function Home() { return <><Navbar/><main>
  <section className="relative flex min-h-screen items-end overflow-hidden bg-olive"><Image src="/images/hill-country-weekend-hero.png" alt="Golden hour over the Wimberley Texas Hill Country" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/25 to-black/35"/><div className="site-shell relative z-10 pb-20 pt-44 text-cream sm:pb-24"><p className="eyebrow text-gold">Wimberley, Texas · Hill Country weekends</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[.92] sm:text-7xl lg:text-[6.4rem]">Experience the<br/><em className="font-normal">Texas Hill Country.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-white/80 sm:text-lg">Private transportation designed around unforgettable days.</p><div className="mt-10 flex flex-wrap gap-4"><Link className="button button-gold" href="#experiences">Explore experiences</Link><Link className="button button-outline" href="/contact">Plan your weekend</Link></div></div></section>
  <section id="experiences" className="py-24 sm:py-36"><div className="site-shell"><div className="max-w-2xl"><p className="eyebrow">Curated experiences</p><h2 className="mt-5 font-serif text-5xl leading-[.98] text-olive sm:text-6xl">Days you’ll talk about long after the weekend ends.</h2><p className="mt-6 leading-7 text-ink/70">The best Hill Country days are felt, not scheduled. We make room for the winery stop that becomes lunch, the concert encore, and the road that leads somewhere unexpected.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{experiences.map(([title, text, image], i) => <Link href="/services" key={title} className={`group relative min-h-[25rem] overflow-hidden ${i === 0 ? "md:col-span-2 lg:col-span-1" : ""}`}><Image src={image} alt="" fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className={`object-cover transition duration-700 group-hover:scale-105 ${i % 2 ? "object-center" : "object-left"}`}/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-black/10"/><div className="absolute inset-x-0 bottom-0 p-7 text-cream"><span className="text-[10px] font-bold tracking-[.22em] text-gold">0{i+1}</span><h3 className="mt-3 font-serif text-3xl">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-white/75">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em]">Explore <ArrowRight size={15}/></span></div></Link>)}</div></div></section>
  <section className="bg-olive py-24 text-cream sm:py-36"><div className="site-shell"><div className="grid gap-9 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-gold">Discover the Hill Country</p><h2 className="mt-5 font-serif text-5xl leading-[.98] sm:text-6xl">Come for a weekend. Find your place.</h2></div><p className="max-w-xl self-end leading-7 text-white/70">From Wimberley’s slow creek mornings to Fredericksburg’s vineyard-filled afternoons, each town holds its own kind of magic. Let the road between them be part of the story.</p></div><div className="mt-16 grid gap-4 md:grid-cols-2">{destinations.map(([name, text], i) => <Link href="/destinations" key={name} className="group relative min-h-80 overflow-hidden border border-white/15 p-8"><Image src={i % 2 ? "/images/hill-country-vineyard.png" : "/images/hill-country-weekend-hero.png"} alt="" fill sizes="(max-width: 768px) 100vw, 50vw" className={`object-cover opacity-65 transition duration-700 group-hover:scale-105 group-hover:opacity-80 ${i === 2 ? "object-left" : "object-center"}`}/><div className="absolute inset-0 bg-olive/40"/><div className="relative flex h-full flex-col justify-end"><span className="mb-auto text-[10px] font-bold tracking-[.25em] text-gold">0{i+1}</span><h3 className="font-serif text-4xl">{name}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/75">{text}</p></div></Link>)}</div></div></section>
  <section className="py-24 sm:py-36"><div className="site-shell"><div className="max-w-2xl"><p className="eyebrow">Made for lingering</p><h2 className="mt-5 font-serif text-5xl leading-[.98] text-olive sm:text-6xl">The luxury is in how the day unfolds.</h2></div><div className="mt-16 grid gap-px overflow-hidden border border-olive/10 bg-olive/10 md:grid-cols-2 lg:grid-cols-4">{reasons.map(([number, title, text]) => <article key={title} className="bg-cream p-8"><span className="text-xs font-bold tracking-[.2em] text-gold">{number}</span><h3 className="mt-14 font-serif text-3xl text-olive">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/65">{text}</p></article>)}</div></div></section>
  <section className="bg-white py-24 sm:py-36"><div className="site-shell relative overflow-hidden bg-charcoal px-7 py-16 text-center text-cream sm:px-14 sm:py-24"><Image src="/images/hill-country-evening.png" alt="Hill Country evening gathering" fill sizes="100vw" className="object-cover opacity-30"/><div className="absolute inset-0 bg-olive/55"/><div className="relative"><Sparkles className="mx-auto text-gold" size={28} strokeWidth={1.3}/><p className="eyebrow mt-6 text-gold">Your weekend awaits</p><h2 className="mx-auto mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-6xl">Let’s plan your perfect day.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-white/75">Tell us what you’re celebrating, exploring, or simply craving. We’ll help make the time between each beautiful stop feel effortless.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><a className="button button-gold" href="tel:+15125550184"><Phone size={15}/> Call us</a><a className="button button-outline" href="sms:+15125550184"><CalendarDays size={15}/> Text us</a><a className="button button-outline" href="mailto:hello@hillcountrychauffeur.com"><Mail size={15}/> Email us</a></div></div></div></section>
</main><Footer/></>; }
