import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Quote } from "lucide-react";
import Navbar from "@/components/Navbar"; import Footer from "@/components/Footer"; import SectionIntro from "@/components/SectionIntro"; import ExperienceGrid from "@/components/ExperienceGrid"; import CTA from "@/components/CTA";
const destinations = ["Wimberley", "Driftwood", "Dripping Springs", "Fredericksburg"];
export default function Home() { return <><Navbar/><main><section className="relative flex min-h-screen items-end overflow-hidden bg-olive"><Image src="/images/wimberley-kia-carnival-road.png" alt="Black Kia Carnival on a wide Wimberley, Texas Hill Country road" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-black/25"/><div className="site-shell relative z-10 pb-16 pt-40 text-cream sm:pb-20"><p className="eyebrow text-gold">Wimberley · Driftwood · Fredericksburg</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.9] sm:text-7xl lg:text-8xl">The Hill Country,<br/><em className="font-normal">at your pace.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/80 sm:text-lg">Thoughtful private transportation for winery days, celebrated evenings, and every beautiful mile in between.</p><div className="mt-10 flex flex-wrap gap-4"><Link className="button button-gold" href="/contact">Plan your experience</Link><Link className="button button-outline" href="/services">Explore services</Link></div></div></section>
<section className="py-20 sm:py-28"><div className="site-shell"><SectionIntro eyebrow="Curated experiences" title="The itinerary is yours. The ease is ours." text="From your first pour to your final stop, every journey is intentionally designed around what you enjoy most."/><ExperienceGrid/></div></section>
<section className="bg-olive py-20 text-cream sm:py-28"><div className="site-shell grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><SectionIntro eyebrow="Featured destinations" title="A more considered way to explore Texas wine country." text="We know the back roads, the best overlooks, and the art of giving a day enough room to unfold."/><div className="grid gap-3 sm:grid-cols-2">{destinations.map((destination, i) => <Link href="/destinations" key={destination} className="group relative min-h-52 overflow-hidden border border-white/15 p-6"><Image src="/images/wimberley-kia-carnival-road.png" alt="" fill sizes="(max-width: 640px) 100vw, 50vw" className={`object-cover opacity-45 transition duration-700 group-hover:scale-110 group-hover:opacity-60 ${i % 2 ? "object-left" : "object-right"}`}/><div className="absolute inset-0 bg-black/25"/><div className="relative flex h-full flex-col justify-between"><span className="text-xs tracking-[.2em] text-gold">0{i+1}</span><span className="flex items-end justify-between font-serif text-3xl">{destination}<ArrowRight size={20}/></span></div></Link>)}</div></div></section>
<section className="py-20 sm:py-28"><div className="site-shell grid gap-12 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Why Hill Country Chauffeur</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight text-olive sm:text-5xl">We believe transportation should feel like hospitality.</h2></div><div className="grid gap-7">{["Private, impeccably kept vehicles","A local team that knows the region intimately","Flexible timing and tailored routes","A calm, elevated experience from door to door"].map(item => <div className="flex gap-4" key={item}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-gold text-white"><Check size={15}/></span><p className="pt-1 text-base text-ink/75">{item}</p></div>)}</div></div></section>
<section className="border-y border-olive/10 bg-white py-20 sm:py-28"><div className="site-shell max-w-4xl text-center"><Quote className="mx-auto text-gold" size={34} strokeWidth={1}/><blockquote className="mt-7 font-serif text-3xl leading-tight text-olive sm:text-5xl">“They transformed a simple tasting day into one of the most memorable parts of our Hill Country weekend.”</blockquote><p className="mt-7 text-xs font-bold tracking-[.2em] text-ink/55 uppercase">— Caroline R., Austin</p></div></section><CTA/></main><Footer/></>; }
